# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
permalink: pretty
exclude: [bin, README.md, LICENSE.txt, CNAME, package.json, node_modules, gulpfile.js, .jshintrc, web-coworking.sublime-project, web-coworking.sublime-workspace ]

# Site Settings
title: "Extreme Coworking - El mejor espacio de coworking en Santa Cruz de Tenerife"
email: "info@extrema-sistemas.com"
description: "Comparte con Extrema Sistemas el mejor espacio de coworking en Santa Cruz de Tenerife"
baseurl: ""
url: "http://tfe.extrema-sistemas.com"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: "tfe.extrema-sistemas.com"

# Head
twitterAccount: "@extremasistemas"

# Main Block
mainImage: "main.jpg"
mainTitle: "Extreme Coworking"
mainSubtitle: "El mejor coworking space en Santa Cruz de Tenerife"
mainButtons:
 - {link: "mailto:info@extrema-sistemas.com", text: "Ponte en contacto", class: "icon-mail"}
 - {permalink: "/#prices", text: "Ver precios", class: "icon-euro"}

# About Block
aboutBlock:
 - {title: "En grupo", icon: "icon-users", text: "Somos un grupo de fanáticos que nos hemos juntado en un espacio para desarrollar software. Cada uno tiene su propia agenda y entregables, pero también nos juntamos para contarnos batallitas."}
 - {title: "Ubicación", icon: "icon-location", text: "En plena Plaza de la Candelaria, literalmente enfrente de la estación de tranvía, a diez minutos del mayor parking gratuito de Santa Cruz. Llegar y volver nunca ha sido tan fácil."}
 - {title: "Fibra", icon: "icon-cog-alt", text: "Contamos con fibra de Telefónica y cableado categoría 6 por toda la oficina. No creemos que sea buena cosa quedarse a medias de subir una release a producción."}

# Location Block
locationBlockTitle: "Location"
streetAddress: "C/ Doctor Allart 16, 3ºE"
addressLocality: "Santa Cruz de Tenerife"
placeCoordinates: "28.466347, -16.2490696"
mapCenterCoordinates: "28.466347, -16.2490696"
mapMobileCenterCoordinates: "28.466347, -16.2490696"
viewOnGoogleMaps: "Ver en Google Maps"

# Office Block
officeBlockTitle: "El espacio"
officeMainImage: "office_0.jpg"
officeImage1: "office_1.jpg"
officeImage2: "office_2.jpg"
officeImage3: "office_3.jpg"

# Prices Block
pricesTitle: "Precios"
pricesOffers:
 -
  name: "Meses sueltos"
  price: "200"
  priceCurrency: "€"
  priceContentList: ["Mes a mes", "Mayor flexibilidad", "Puesto asignado", "Fibra óptica", "Linea telefónica"]
 -
  name: "Trimestral"
  price: "160"
  priceCurrency: "€"
  ribbon: "-20%"
  featured: true
  priceContentList: ["3+ meses", "Opción equilibrada", "Puesto asignado", "Fibra óptica", "Linea telefónica"]
 -
  name: "Anual"
  price: "125"
  priceCurrency: "€"
  ribbon: "37%"
  priceContentList: ["12+ meses", "Mayor ahorro", "Puesto asignado", "Fibra óptica", "Linea telefónica"]
