# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
permalink: pretty
exclude: ['/bin/', 'README.md', 'LICENSE.txt', 'CNAME', 'package.json', '/node_modules/', 'gulpfile.js', '.jshintrc', 'web-coworking.sublime-project', 'web-coworking.sublime-workspace']

# Site Settings
title: "Coworking space in Santa Cruz de Tenerife"
email: "info@extrema-sistemas.com"
description: "Coworking space in Santa Cruz de Tenerife"
baseurl: ""
url: "http://tfe.extrema-sistemas.com"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: "tfe.extrema-sistemas.com"

# Head
metaKeywords: "coworking, space, tenerife, extrema, sistemas"
twitterAccount: "@extremasistemas"

# Main Block
mainImage: "main.jpg"
mainTitle: "Coworking space"
mainSubtitle: "Santa Cruz de Tenerife"
mainButtons:
 - {link: "mailto:info@extrema-sistemas.com", text: "Get in contact", class: "icon-mail"}
 - {permalink: "/#prices", text: "See prices", class: "icon-euro"}

# About Block
aboutTitle: "About Extrema Sistemas Coworking space"
aboutDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam elementum lorem porttitor quam tempor vehicula. Sed sagittis, lacus vel pretium hendrerit, quam erat porta neque, at mollis dolor turpis ac quam. Curabitur lacus mi, semper laoreet faucibus et, bibendum at."
aboutBlock:
 - {title: "Group", icon: "icon-users", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam elementum lorem porttitor quam tempor vehicula. Sed sagittis, lacus vel pretium hendrerit, quam erat porta neque, at mollis dolor turpis ac quam. Curabitur lacus mi, semper laoreet faucibus et, bibendum at."}
 - {title: "Location", icon: "icon-location", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam elementum lorem porttitor quam tempor vehicula. Sed sagittis, lacus vel pretium hendrerit, quam erat porta neque, at mollis dolor turpis ac quam. Curabitur lacus mi, semper laoreet faucibus et, bibendum at."}
 - {title: "Settings", icon: "icon-cog-alt", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam elementum lorem porttitor quam tempor vehicula. Sed sagittis, lacus vel pretium hendrerit, quam erat porta neque, at mollis dolor turpis ac quam. Curabitur lacus mi, semper laoreet faucibus et, bibendum at."}

# Location Block
locationBlockTitle: "Location"
streetAddress: "C/ Doctor Allart 16, 3ºE"
addressLocality: "Santa Cruz de Tenerife"
placeCoordinates: "28.466347, -16.2490696"
mapCenterCoordinates: "28.466347, -16.2490696"
mapMobileCenterCoordinates: "28.466347, -16.2490696"
viewOnGoogleMaps: "View on Google Maps"

# Office Block
officeBlockTitle: "Office"
officeMainImage: "office_0.jpg"
officeImage1: "office_1.jpg"
officeImage2: "office_2.jpg"
officeImage3: "office_3.jpg"

# Prices Block
pricesTitle: "Prices"
pricesOffers:
 -
  name: "Daily"
  price: "50"
  priceCurrency: "EUR"
  ribbon: "-5%"
  priceContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
 -
  name: "Monthly"
  price: "200"
  priceCurrency: "EUR"
  ribbon: "-20%"
  featured: true
  priceContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
 -
  name: "Hourly"
  price: "15"
  priceCurrency: "EUR"
  priceContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
